/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: scvrJqaRVcGNwFCfthLLKU

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantslerhodZCeyt2 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: LerhodZCeyt2/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantslerhodZCeyt2
});
